[package]
name = "lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
tempfile = "3.3.0"
thiserror = "1.0.38"
tracing = "0.1.37"
wasmtime = "5.0.0"
